---
title: Zalewski
pagetitle: Zalewski - Usługi księgowe skrojone na miarę
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Usługi księgowe skrojone na miarę
owner: Zalewski
first_published: 2016
email: michal_zalewski@interia.pl
baseurl: ''
url: http://yourdomain.com
social:
  linkedin-square: https://pl.linkedin.com/in/michał-zalewski-07374710a/en
#  facebook-official: https://facebook.com/<zalewski-page>
  email: mailto:michal_zalewski@interia.pl
markdown: kramdown
