---
title: Zalewski
#Landing page use page.title instead of below config due to SEO constraints
pagetitle: Zalewski - Usługi księgowe skrojone na miarę
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Usługi księgowe skrojone na miarę
owner: Zalewski
first_published: 2016
email: michal_zalewski@interia.pl
baseurl: ''
url: http://michalzalewski.pl/
social:
  linkedin-square: https://pl.linkedin.com/in/michał-zalewski-07374710a/en
  facebook-official: https://www.facebook.com/BRZalewski/
  email: mailto:kontakt@michalzalewski.pl
markdown: kramdown
