---
title: Zalewski
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: |
  Indywidualne usługi księgowe
owner: Zalewski
first_published: 2016
email: michal@zalewski.it
baseurl: ''
url: http://yourdomain.com
social:
  linkedin-square: https://pl.linkedin.com/in/michał-zalewski-07374710a/en
  facebook-official: https://facebook.com/<zalewski-page>
  email: michal@zalewski.it
markdown: kramdown
